"""CLI entry point: ``python -m revit_schema_mapper``.

This is the single command referenced in the project's definition of done:
it runs discovery, crawl, parse, classify, and export in one shot and is
resumable (re-running it will reuse the on-disk HTML cache and only fetch
what's missing).
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

from .community import DEFAULT_OPENROUTER_MODEL
from .crawl import CrawlConfig
from .http_compat import HAVE_REQUESTS
from .pipeline import (
    DEFAULT_KNOWN_EDGE_CHECKS,
    DEFAULT_TARGET_CLASSES,
    run_discovery,
    run_graph_only,
    run_pipeline,
    run_targeted_pipeline,
)

try:
    import bs4 as _bs4  # noqa: F401

    HAVE_BS4 = True
except ImportError:
    HAVE_BS4 = False

KNOWN_FALLBACK_REASON = (
    "Revit 2027 API docs were not confirmed reachable/structurally consistent at build time; "
    "falling back to 2026. Document why in docs/crawl_notes.md if this triggers for a real run."
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Crawl, parse, and classify the Autodesk.Revit.DB API surface from RevitApiDocs.")
    parser.add_argument("--version", default="2027", help="Revit version path segment on revitapidocs.com (default: 2027)")
    parser.add_argument("--output-dir", default=None, help="Output directory (default: outputs/revit_<version>/ relative to repo root)")
    parser.add_argument("--cache-dir", default=None, help="HTML cache directory (default: <output-dir>/cache)")
    parser.add_argument("--namespace-prefix", default="Autodesk.Revit.DB", help="Only keep pages whose namespace starts with this prefix")
    parser.add_argument("--throttle-seconds", type=float, default=1.5, help="Minimum delay between HTTP requests")
    parser.add_argument("--max-pages", type=int, default=None, help="Cap on total pages fetched (useful for smoke tests)")
    parser.add_argument("--force-refresh", action="store_true", help="Re-fetch pages even if already cached")
    parser.add_argument("--fallback-reason", default=None, help="If set, records why this run is a documented fallback (e.g. from 2027 to 2026)")
    parser.add_argument(
        "--targeted-validation",
        action="store_true",
        help="Run a scoped validation crawl against a fixed list of target classes plus a known-edge test report, instead of a full namespace crawl",
    )
    parser.add_argument(
        "--target-classes",
        default=None,
        help="Comma-separated fully-qualified class names to use with --targeted-validation, overriding the default list",
    )
    parser.add_argument(
        "--discover-only",
        action="store_true",
        help="Only run page discovery and report how many pages a full run would need to fetch -- "
        "does not fetch/parse individual pages or write anything but raw_index.json",
    )
    parser.add_argument(
        "--graph-only",
        action="store_true",
        help="Recompute graph.json/graph_core.json (and refresh the summary's graph section) from "
        "this output directory's existing node_type_candidates.json/candidate_edges.json, without "
        "crawling or re-parsing anything -- much faster than a full re-run when only graph.py "
        "changed, especially on slow hardware. Requires a previous run's output to already exist "
        "in --output-dir.",
    )
    parser.add_argument(
        "--include-doc-text",
        action="store_true",
        help="Include full summary/remarks/code-example text (copied from the docs site) in "
        "api_pages.json. Omitted by default -- these are prose/code, not derived facts -- "
        "so only opt in for local debugging, and don't republish the result.",
    )
    parser.add_argument(
        "--label-communities-llm",
        action="store_true",
        help="Upgrade community labels from the default free heuristic (most-connected member "
        "names) to a short label generated by an OpenRouter model. Requires OPENROUTER_API_KEY "
        "to be set in the environment (never passed as a flag, to keep it out of shell history) -- "
        "falls back to the heuristic label with a warning if it isn't. Only fires once, on the "
        "final checkpoint of a run, not on every periodic checkpoint of a long crawl.",
    )
    parser.add_argument(
        "--community-label-model",
        default=DEFAULT_OPENROUTER_MODEL,
        help=f"OpenRouter model id used with --label-communities-llm (default: {DEFAULT_OPENROUTER_MODEL}, "
        "a small/inexpensive model as of writing -- OpenRouter's catalog and pricing change over "
        "time, so double-check and override this if needed)",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO if args.verbose else logging.WARNING, format="%(levelname)s %(name)s: %(message)s")

    log = logging.getLogger(__name__)
    log.info("HTTP backend: %s", "requests" if HAVE_REQUESTS else "urllib.request (stdlib fallback -- requests not installed)")
    log.info("HTML backend: %s", "beautifulsoup4" if HAVE_BS4 else "html_compat (stdlib fallback -- beautifulsoup4 not installed)")

    targeted = args.targeted_validation or args.target_classes is not None

    default_output_name = f"revit_{args.version}_targeted" if targeted else f"revit_{args.version}"
    output_dir = Path(args.output_dir) if args.output_dir else Path(f"outputs/{default_output_name}")
    cache_dir = Path(args.cache_dir) if args.cache_dir else output_dir / "cache"

    openrouter_api_key = os.environ.get("OPENROUTER_API_KEY")

    if args.graph_only:
        if not (output_dir / "node_type_candidates.json").exists() or not (output_dir / "candidate_edges.json").exists():
            print(f"error: {output_dir} has no node_type_candidates.json/candidate_edges.json to rebuild from -- run a real crawl first", file=sys.stderr)
            return 1
        result = run_graph_only(
            output_dir,
            revit_version=args.version,
            label_communities_llm=args.label_communities_llm,
            community_label_model=args.community_label_model,
            openrouter_api_key=openrouter_api_key,
        )
        print(f"Nodes:              {len(result.nodes)} ({result.external_node_count} external)")
        print(f"Edges:              {len(result.edges)}")
        print(f"Target resolution:  {result.target_resolution_counts}")
        print(f"Communities:        {len(result.communities)}")
        print(f"Outputs written to: {output_dir / 'graph.json'} / {output_dir / 'graph_core.json'} / {output_dir / 'graph.html'}")
        return 0

    config = CrawlConfig(
        version=args.version,
        namespace_prefix=args.namespace_prefix,
        cache_dir=cache_dir,
        throttle_seconds=args.throttle_seconds,
        max_pages=args.max_pages,
        force_refresh=args.force_refresh,
    )

    if args.discover_only:
        result = run_discovery(config, output_dir)
        print(f"Pages discovered: {len(result.raw_index_entries)}")
        for source, count in sorted(result.counts_by_source.items(), key=lambda kv: -kv[1]):
            print(f"  {source}: {count}")
        if result.discovery_errors:
            print(f"Discovery errors ({len(result.discovery_errors)}):")
            for err in result.discovery_errors:
                print(f"  {err}")
        print(f"Raw index written to: {output_dir / 'raw_index.json'}")
        return 0

    if targeted:
        target_classes = [t.strip() for t in args.target_classes.split(",") if t.strip()] if args.target_classes else DEFAULT_TARGET_CLASSES
        result = run_targeted_pipeline(
            config,
            output_dir,
            target_full_type_names=target_classes,
            known_edge_checks=DEFAULT_KNOWN_EDGE_CHECKS,
            include_doc_text=args.include_doc_text,
            label_communities_llm=args.label_communities_llm,
            community_label_model=args.community_label_model,
            openrouter_api_key=openrouter_api_key,
        )

        targets_found = sum(1 for t in result.target_report if t.found_in_namespace_json)
        targets_parsed = sum(1 for t in result.target_report if t.class_page_parsed)
        edges_found = sum(1 for k in result.known_edge_report if k.edge_produced)
        print(f"Target classes:      {len(target_classes)} ({targets_found} found in index, {targets_parsed} parsed)")
        print(f"Known-edge checks:   {len(result.known_edge_report)} ({edges_found} produced an edge)")
        print(f"Pages discovered:    {len(result.raw_index_entries)}")
        print(f"Pages parsed:        {len(result.pages)}")
        print(f"Node candidates:     {len(result.node_candidates)}")
        print(f"Edge candidates:     {len(result.edge_candidates)}")
        print(f"Failed pages:        {len(result.failed_urls)}")
        print(f"Outputs written to: {output_dir} (see validation_summary.md)")
        return 0

    result = run_pipeline(
        config,
        output_dir,
        fallback_reason=args.fallback_reason,
        include_doc_text=args.include_doc_text,
        label_communities_llm=args.label_communities_llm,
        community_label_model=args.community_label_model,
        openrouter_api_key=openrouter_api_key,
    )

    print(f"Pages discovered: {len(result.raw_index_entries)}")
    print(f"Pages parsed:     {len(result.pages)}")
    print(f"Node candidates:  {len(result.node_candidates)}")
    print(f"Edge candidates:  {len(result.edge_candidates)}")
    print(f"Failed pages:     {len(result.failed_urls)}")
    print(f"Outputs written to: {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
